mybatis-plus:
  global-config:
    db-config:
      id-type: auto

spring:
  main:
    allow-circular-references: true
  application:
    name: labserver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      location: /home/zjy/Workspace/labserver/frontend/resources/imgs

  datasource:
    url: jdbc:mysql://localhost:3306/labserver?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: Asia/Shanghai

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0

server:
  port: 8403

dockerRoot: "/home/zjy/Workspace/labserver/"
resourcesPath: "/home/zjy/Workspace/labserver/frontend/resources/"